FROM python:3.7-slim

ENV PYTHONPATH /app
ENV PYTHONUNBUFFERED 1

COPY ./flask_server/requirements.txt /app/requirements.txt
RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt

COPY common /common

RUN mkdir /output
WORKDIR /output

ENV FLASK_APP=/app/server.py

CMD ["gunicorn", "-b", ":5000", "server:app"]
