FROM python:3.7-slim

ENV PYTHONUNBUFFERED 1

COPY ./web_server/requirements.txt /app/requirements.txt
RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt

#COPY common /common

RUN mkdir /output
WORKDIR /output

ENV FLASK_APP=/app/server.py
ENV FLASK_ENV=development

ENV PYTHONPATH /app:/common:/lenticular_lens_1

COPY ./web_server/src /app
CMD ["gunicorn", "-b", ":8000", "--reload", "server:app"]
