FROM python:3.7-slim

ENV PYTHONPATH /common
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y procps
COPY ./jobs_worker/requirements.txt /app/requirements.txt
RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt

RUN mkdir /output
WORKDIR /output

COPY common /common

COPY ./jobs_worker/src /app
CMD ["python", "/app/jobs_worker.py"]