FROM python:3.7-slim

ENV PYTHONPATH /common
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y procps
COPY ./timbuctoo_worker/requirements.txt /app/requirements.txt
RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt

COPY common /common

RUN mkdir /output
WORKDIR /output

COPY ./timbuctoo_worker/src /app

CMD ["python", "/app/timbuctoo_worker.py"]