[tool.poetry]
name = "lenticular-lens"
version = "1.18"
description = ""
readme = "readme.md"
package-mode = false
packages = [
    { include = "lenticularlens" }
]

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"
flask-cors = "^5.0.0"
flask-pyoidc = "^3.14.3"
flask-socketio = "^5.4.1"
eventlet = "^0.39.1"
cachetools = "^5.5.0"
schema = "^0.7.7"
kitchen = "^1.2.6"
psycopg = {version = "^3.2.3", extras = ["binary"]}
psycopg_pool = "^3.2.1"
networkx = "^3.3"
pyyaml = "^6.0.2"
pydantic = "^2.11.2"
python-intervals = "^1.10.0.post1"
rdflib = "^7.1.4"
requests = "^2.32.3"
unidecode = "^1.3.8"
xmltodict = "^0.14.2"
urllib3 = "^2.2.3"
anytree = "^2.12.1"
sparqlwrapper = "^2.0.0"

[tool.poetry.group.web]
optional = true

[tool.poetry.group.web.dependencies]
gunicorn = "^23.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
