[tool.poetry]
name = "lenticular-lens"
version = "1.21"
description = ""
readme = "readme.md"
package-mode = false
packages = [
    { include = "lenticularlens" }
]

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.118.1"
uvicorn = "^0.37.0"
python-multipart = "^0.0.20"
authlib = "^1.6.5"
python-socketio = "^5.14.1"
brotli-asgi = "^1.4.0"
cachetools = "^6.2.0"
schema = "^0.7.7"
kitchen = "^1.2.6"
psycopg = { version = "^3.2.10", extras = ["binary"] }
psycopg_pool = "^3.2.1"
networkx = "^3.5"
pyyaml = "^6.0.3"
pydantic = "^2.11.10"
python-intervals = "^1.10.0.post1"
rdflib = "^7.2.1"
requests = "^2.32.4"
unidecode = "^1.3.8"
xmltodict = "^0.14.2"
urllib3 = "^2.5.0"
anytree = "^2.12.1"
itsdangerous = "^2.2.0"
httpx = "^0.28.1"
pyld = "^2.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
